name:   DoE
channels:
  - conda-forge
  - nvidia
  - pytorch
  - pip
dependencies:
  - nvidia::cudatoolkit=10.2
  - python=3.7
  - pytorch::pytorch=1.12.1
  - torchvision=0.13.1
  - matplotlib=3.5.2
  - pip:
      - opencv-python==4.6.0.66
  